---
driver:
  name: vagrant
  customize:
      memory: 512

provisioner:
  name: chef_zero
  chef_zero_port: 9010

platforms:
  - name: centos-6.6
    driver:
      network:
      - ["private_network", {ip: "33.33.33.25"}]

suites:
  - name: default
    run_list:
      - recipe[yum-gd]
      - recipe[build-essential]
      - recipe[test-helper::default]
      - recipe[python::default]
      - recipe[python-deployment::default]
    attributes:
      python-deployment:
        application:
          name: appserv-feeds
          settings: appserv_feeds.settings
          dependencies:
            - libmemcached-devel
          version: latest
          framework: django
          repository: http://pypi.awsdev.usatoday.com
        process-application: true
      python:
        version: 2.7.9-1.el6.gd
        install_method: custom-package
  - name: uwsgi
    run_list:
      - recipe[yum-gd]
      - recipe[build-essential]
      - recipe[test-helper::default]
      - recipe[python::default]
      - recipe[uwsgi::default]
      - recipe[nginx::default]
      - recipe[python-deployment::default]
      - recipe[uwsgi::init]
    attributes:
      python-deployment:
        application:
          name: appserv-feeds
          settings: appserv_feeds.settings
          dependencies:
            - libmemcached-devel
          version: latest
          framework: django
          repository: http://pypi.awsdev.usatoday.com
          config_location: remote
        uwsgi-application: true
      python:
        version: 2.7.9-1.el6.gd
        install_method: custom-package
  - name: scalr
    run_list:
      - recipe[yum-gd]
      - recipe[build-essential]
      - recipe[test-helper::default]
      - recipe[python::default]
      - recipe[uwsgi::default]
      - recipe[nginx::default]
      - recipe[python-deployment::default]
      - recipe[uwsgi::init]
    attributes:
      scalr:
        check-command: "echo scalr"
      python-deployment:
        application:
          name: appserv-feeds
          settings: appserv_feeds.settings
          dependencies:
            - libmemcached-devel
          version: latest
          framework: django
          repository: http://pypi.awsdev.usatoday.com
          config_location: remote
        uwsgi-application: true
      python:
        version: 2.7.9-1.el6.gd
        install_method: custom-package
