---
driver:
  name: vagrant
  customize:
      memory: 512

provisioner:
  name: chef_zero
  chef_zero_port: 9010

platforms:
  - name: centos-6.6
    driver:
      network:
      - ["private_network", {ip: "33.33.33.25"}]

suites:
  - name: default
    run_list:
      - recipe[yum-gd]
      - recipe[java]
      - recipe[grails]
    attributes:
      tomcat:
        base_version: 7
        user: tomcat
        group: tomcat
        java_options: -server -Xms2048m -Xmx2048m -XX:PermSize=512m -XX:MaxPermSize=1024M -Djava.awt.headless=true -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=9005 -DJENKINS_HOME=/.jenkins -Dmail.smtp.starttls.enable=true -Duser.timezone=GMT-5
      java:
        jdk_version: 7
        install_flavor: oracle
        oracle:
          accept_oracle_download_terms: true
